[build]
command = "cargo install -q worker-build && worker-build --release"

[env.production]
name = "images-proxy"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

[env.preview]
name = "images-proxy-preview"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"
