name: wrangler

on:
  push:
    branches:
      - main

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo fmt --all --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo clippy

  deploy:
    needs: [fmt, clippy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        uses: ker0olos/wrangler-action@b11b972b44a5d7a5c5fff4b6f92d5ba11483c370
        # env:
        #   SECRET1: ${{ secrets.SECRET1 }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          # secrets: |
          #   SECRET1
