name: wrangler

on: [push]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo fmt --all --check

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo check

  deploy:
    needs: [fmt, check]
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        uses: ker0olos/wrangler-action@79ab8d9ea54478069c2afe2bcaaa475514c9638d
        # env:
        #   SECRET1: ${{ secrets.SECRET1 }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          # secrets: |
          #   SECRET1
