name: wrangler

on: [push]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo fmt --all --check

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo check

  deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    environment: 
      name: production
      url: https://images-proxy.fables.workers.dev
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Cloudflare Workers
        uses: ker0olos/wrangler-action@79ab8d9ea54478069c2afe2bcaaa475514c9638d
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
