name: wrangler

on:
  push:
    branches:
      - main

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo fmt --all --check

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo check

  deploy:
    needs: [fmt, check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        uses: ker0olos/wrangler-action@20c71e394eba7b3dd07f25ca40f047dbc70eb493
        # env:
        #   SECRET1: ${{ secrets.SECRET1 }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          # secrets: |
          #   SECRET1
